### ISSUE TITLE
Lab 1 Screenshots

### ISSUE THREAD

**Issue by CSinclair89** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-CSinclair89#1]
![lab1 image1](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-CSinclair89/assets/97923131/18a38356-149f-40ef-a14c-c879fd608f79)
![lab1 image2](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-CSinclair89/assets/97923131/9feb1ea9-4b59-4e1c-bd80-c5062088427a)

Hey Chris,

Here are screenshots of the Git commands for Lab 1.

**Comment by instructorc** [comment]
Deliverable 1 met!
