### ISSUE TITLE
Lab 1 Screenshot - Deliverable #2

### ISSUE THREAD

**Issue by CSinclair89** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-CSinclair89#2]
![lab1 image3](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-CSinclair89/assets/97923131/3d7771e1-1d70-4a45-9f60-957f92961005)

 Here is the screenshot for deliverable #2.

**Comment by instructorc** [comment]
Deliverable 2 met
